services:
  - type: web
    name: camera-bubble-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BUBBLE_WEBHOOK_URL
        value: https://sua-app.bubbleapps.io/api/1.1/wf/webhook-camera
    healthCheckPath: /health
